### ISSUE TITLE
PINE64 PineBuds Pro, Microphone's noise

### ISSUE THREAD

**Issue by lizz-34** [pine64/OpenPineBuds#35]
This kind of noise comes from the microphone.
Listen: https://sndup.net/ywxx/

--
Info
Device: PINE64 PineBuds Pro

**Comment by WebWire-NL** [comment]
Hi @lizz-34,
I think it's better to continue your questions on reddit.
https://www.reddit.com/r/pine64official
This is more about the firmware which is being created, most of the questions you asked could be discussed on reddit
There's a difference between this project and the product itself as delivered by pine64, i'm sure if any discussion on /r/pine64official leads to a possible change in the open source code will come to the attention over here. This way the project get's related with non related issues. You can also ask questions what's the difference between the open source version and this project. (no offense)

**Comment by lizz-34** [comment]
> I think it's better to continue your questions on reddit.
https://www.reddit.com/r/pine64official
This is more about the open source firmware which is being created, most of the questions you asked could be discussed on reddit

I know and I do ask my hardware questions elsewhere, but I think this might be a software bug.

> You can also ask questions about the difference between the open source version and this project and answered questions like the one you are asking now.

Open source version and this project is the same? What do you mean?

>  (no offense)

Tbh I'm afraid I'm burdening you and others. I have asked a lot of possibly stupid questions... This has never been done before and there is so much new and strange for a novice like me.

**Comment by WebWire-NL** [comment]
I meant the release product including the original firmware (with ANC) for the pinebuds with ANC and the open source version (this repository on github).
There's no stupid questions, just not the right place to discuss them :) I was also confused at the beginning. But there's a product (pinebuds pro) with firmware (proprietary/closed source firmware) sold by pine64 which can be discussed at reddit, and there's this open source software which is a totally different project.

**Comment by lizz-34** [comment]
> I meant the release product including the original firmware (with ANC) for the pinebuds with ANC and the open source version (this repository on github).

Oh, noise is recorded from PineBuds Pro with this open-source firmware. I agree, discussion about the pre-installed propietary firmware of PineBuds Pro doesn't belong here.

>  There's no stupid questions, just not the right place to discuss them :) I was also confused at the beginning. But there's a product (pinebuds pro) with firmware (proprietary/closed source firmware) sold by pine64 which can be discussed at reddit, and there's this open source software which is a totally different project.

Glad to hear. If you have time, could you sometime try to answer to the rest of my questions (preferably with quote reply, so no ambiguities then)? I know they are long, but I don't think I can get a better answer elsewhere. In the internet isn't much material about these devices, because everything is closed and proprietary...

**Comment by lizz-34** [comment]
**Off-topic**

If you haven't already, I recommend joining to the [PineBuds Pro room on Matrix](https://wiki.pine64.org/wiki/Main_Page#Chat_Platforms), Discrod or Telegram. There's a lot of discussion going on there that might be of interest to you.

**Comment by lizz-34** [comment]
**Off-topic**

If you haven't already, I recommend joining to the [PineBuds Pro room on Matrix](https://wiki.pine64.org/wiki/Main_Page#Chat_Platforms), Discrod or Telegram. There's a lot of discussion going on there that might be of interest to you.

**Comment by WebWire-NL** [comment]
Great so everybody let's discuss over there instead of creating new issue's!
Joined but haven't seen u yet :)

**Comment by lizz-34** [comment]
> @lizz-34 Great tip! so everybody let's discuss over there instead of creating new issue's!

We already do. AFAIK this is software problem and because of that I made an issue.

**Comment by WebWire-NL** [comment]
If it's an issue in the original firmware also this should be addressed at pine64. Anyway i'm out of here for a while :) don't forget a lot of people are doing this on best effort without being paid.

**Comment by lizz-34** [comment]
> @lizz-34 If it's an issue in the original firmware also this should be addressed at pine64.

What? I just said that noise is recorded PineBuds Pro with this open firmware, OpenPineBuds.

> Anyway i'm out of here for a while :) don't forget a lot of people are doing this on best effort without being paid.

Okay, see you again :) Re to?

**Comment by scm2409** [comment]
I'm having the same issue, but I'm pretty sure the noise didn't start right after uploading this firmware.
Reflashing this firmware didn't resolve the problem.

**Comment by hmpthcs** [comment]
I can confirm the same issue with my pinebuds. 
___
Here's what I've noted:
- With stock firmware, the same noise is audible whenever the mic picks up noise/speech. This noise is gone at baseline/'silent' mics.
- With the open source firmware, the mic noise is present at all times--baseline as well as during speech.
- With the open source firmware, the mic signal is grotesquely distorted; using offboard voice isolation (e.g., on an iPhone), I am told that my voice is actually quite clear compared to the stock firmware.

Thus I believe there is work to be done in the mic signal processing, as apparently intelligible or even clear audio _can_ be rendered from even the junky-sounding audio I got in my recordings. Something in the software has clearly changed this; also, I have never dropped my buds and have used them minimally since purchasing.

___

Added links comparing mic recordings with stock vs. open source firmware:
- [stock firmware](https://sndup.net/dpjzx/)
- [open source firmware](https://sndup.net/crbxp/)

**Comment by WebWire-NL** [comment]
From the prebuilt side, this is expected - and the analysis says exactly why, plus where the interfaces are.

This tree links 23 closed `*.a` archives and they were compiled with `-g`, so they still name their own sources: 498 files that the tree does not ship. 130 of those are the mic-side DSP:

    services/multimedia/speech/src          (130 files) - 2/3-mic noise suppression, far-field speech enhancement, wind detection, mic calibration, DC filter
    services/multimedia/audio/process        (27 files) - the ANC / mic processing objects, HW+SW IIR/FIR EQ

The tree ships the headers and the config for these modules but not the implementations, so the open firmware's mic path runs whatever the blobs do, and the stock chain's calibration / NS / EQ stages are closed code the tree cannot configure. That is consistent with @hmpthcs's A/B report: clear from stock, distorted even at baseline in the open firmware.

Two things from the analysis that may be directly useful:

- **The interfaces are recoverable even though the implementations are not.** 593 ANC/DSP prototypes with return types, argument types and source lines, and 31 generated headers (2/3-mic denoise, far-field enhancement, wind detection, mic calibration, DC filter, HW/SW IIR+FIR EQ):
  https://github.com/WebWire-NL/openpinebuds-integration/blob/main/docs/anc-prototypes.md
  https://github.com/WebWire-NL/openpinebuds-integration/tree/main/include/anc_reconstructed
  That is enough to drive or replace stages - not to read them. No implementation here is public anywhere.

- **The mic-path experiments already in the fork network**: BreezeLabsAG's `ph_dsp_bypass`, `SPEECH_TX_EQ_approach` and `SPEECH_TX_MIC_CALIBRATION_approach` branches - DSP bypass, speech TX EQ override, mic calibration. We replay all of them as patch series and record the result; the two SPEECH_TX_ branches replay clean:
  https://github.com/WebWire-NL/openpinebuds-integration/blob/main/docs/patch-status.md
  Use the branches upstream - the patches are only a reviewable snapshot.

Also: 264 of the closed objects call `hal_trace_printf`, so a trace log will show which blob DSP functions are actually active at baseline vs. during speech on a given unit. That is a cheap way to separate "un-calibrated capsule path" from "a processing stage that is running while it should not".

Full material, the 498-file list and the scripts that regenerate it: https://github.com/WebWire-NL/openpinebuds-integration (summary now in the tree as pine64/OpenPineBuds#126).

If this saves anyone work, please credit @WebWire-NL and link the repo - it is spare-time work by one person. Metadata only: no vendor source, no decompiled code, no binaries.
